const nodeSelect=document.getElementById("nodeSelect");
const el=id=>document.getElementById(id);
let selectedNode="NODE_01";
function setConnection(ok){el("connectionText").textContent=ok?"Backend connected":"Waiting for backend";el("connectionDot").style.background=ok?"#5ad38e":"#e7b44a"}
function value(id,v,digits=2){el(id).textContent=Number(v).toFixed(digits)}
function updateStatus(s){
 const tier=s.risk_tier;selectedNode=s.node_id;el("riskTier").textContent=tier;el("riskCard").className="risk-card "+String(tier).toLowerCase();
 el("riskConfidence").textContent="Confidence "+(s.confidence*100).toFixed(1)+"% • "+s.prediction_source;
 el("occupancy").textContent=s.occupied?"Occupied":"Unoccupied";el("explanation").textContent=s.explanation;
 el("modelBadge").textContent=s.model_loaded?"LSTM available":"Baseline safety fallback";el("warmup").textContent="Window: "+s.window_size+"/40";el("explanationMethod").textContent=s.explanation_method;
 value("mq2",s.mq2,3);value("mq7",s.mq7,3);value("temperature",s.temperature,1);value("humidity",s.humidity,1);value("latency",s.latency_ms,2);el("flame").textContent=s.flame?"Detected":"Clear";
 el("contributors").innerHTML=(s.contributors||[]).slice(0,3).map(function(c){return '<div class="contribution"><div class="contribution-line"><span>'+c.feature+'</span><span>'+Number(c.contribution).toFixed(1)+'%</span></div><div class="bar"><span style="width:'+Math.min(100,c.contribution)+'%"></span></div></div>'}).join("");
}
function drawChart(rows){const canvas=el("trendChart"),ctx=canvas.getContext("2d"),width=canvas.width,height=canvas.height,pad=35;ctx.clearRect(0,0,width,height);ctx.strokeStyle="#24334e";ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad+i*(height-2*pad)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(width-pad,y);ctx.stroke()}if(rows.length<2)return;[{key:"mq2",color:"#ef8354",scale:v=>v},{key:"mq7",color:"#ad7ff2",scale:v=>v},{key:"temperature",color:"#54c7ec",scale:v=>Math.max(0,Math.min(1,(v-20)/60))}].forEach(function(item){ctx.strokeStyle=item.color;ctx.lineWidth=3;ctx.beginPath();rows.forEach(function(row,i){const x=pad+i*(width-2*pad)/(rows.length-1),y=height-pad-item.scale(Number(row[item.key]))*(height-2*pad);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
function updateHistory(rows){el("eventCount").textContent=rows.length+" recent events";el("historyBody").innerHTML=rows.slice().reverse().slice(0,12).map(function(r){return "<tr><td>"+new Date(r.timestamp).toLocaleTimeString()+"</td><td>"+r.risk_tier+"</td><td>"+Number(r.mq2).toFixed(3)+"</td><td>"+Number(r.mq7).toFixed(3)+"</td><td>"+Number(r.temperature).toFixed(1)+"°</td><td>"+(r.occupied?"Yes":"No")+"</td></tr>"}).join("")}
async function refreshNodes(){const response=await fetch("/nodes"),nodes=await response.json();if(nodes.length){const current=nodeSelect.value;nodeSelect.innerHTML=nodes.map(function(n){return '<option value="'+n.node_id+'">'+n.node_id+"</option>"}).join("");if(nodes.some(n=>n.node_id===current))nodeSelect.value=current;selectedNode=nodeSelect.value}}
async function refresh(){try{await refreshNodes();const responses=await Promise.all([fetch("/nodes/"+selectedNode+"/status"),fetch("/nodes/"+selectedNode+"/history?limit=50"),fetch("/metrics/summary")]);if(responses[0].status===404){setConnection(true);return}if(!responses[0].ok)throw new Error("status");const data=await Promise.all(responses.map(r=>r.json())),status=data[0],history=data[1],metrics=data[2];updateStatus(status);updateHistory(history);drawChart(history);el("totalPredictions").textContent=metrics.total_predictions;el("averageLatency").textContent=metrics.average_latency_ms+" ms";el("p95Latency").textContent=metrics.p95_latency_ms+" ms";setConnection(true)}catch(error){setConnection(false)}}
nodeSelect.addEventListener("change",function(){selectedNode=nodeSelect.value;refresh()});refresh();setInterval(refresh,2000);
